# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  config.ssh.forward_agent = true
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.define "nagioscentral" do |nagioscentral|
     config.vm.hostname = "nagios-central"
     config.vm.network "forwarded_port", guest: 80, host: 8080
     config.vm.network "private_network", type: "dhcp"
  end

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end
end
