# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  config.ssh.forward_agent = true
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.define "uno" do |uno|
    config.vm.hostname = "nodo-uno"
#    config.vm.network "private_network", ip: "192.168.1.151"
     config.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "dos" do |dos|
    config.vm.hostname = "nodo-dos"
    config.vm.network "private_network", type: "dhcp"
  end

#  config.vm.post_up_message = "Welcome Daniel!"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end
end
