# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  config.vm.define "uno" do |uno|
    config.vm.hostname = "nodo-uno"
    config.vm.network "private_network", ip: "172.28.128.3"
  end

  config.vm.define "dos" do |dos|
    config.vm.hostname = "nodo-dos"
    config.vm.network "private_network", ip: "172.28.128.4", name: "vboxnet3", adapter: 2
  end

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end
end
